/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'hsl(var(--color-primary-50) / <alpha-value>)',
          100: 'hsl(var(--color-primary-100) / <alpha-value>)',
          200: 'hsl(var(--color-primary-200) / <alpha-value>)',
          300: 'hsl(var(--color-primary-300) / <alpha-value>)',
          400: 'hsl(var(--color-primary-400) / <alpha-value>)',
          500: 'hsl(var(--color-primary-500) / <alpha-value>)',
          600: 'hsl(var(--color-primary-600) / <alpha-value>)',
          700: 'hsl(var(--color-primary-700) / <alpha-value>)',
          800: 'hsl(var(--color-primary-800) / <alpha-value>)',
          900: 'hsl(var(--color-primary-900) / <alpha-value>)',
        },
        accent: {
          50: 'hsl(var(--color-accent-50) / <alpha-value>)',
          100: 'hsl(var(--color-accent-100) / <alpha-value>)',
          200: 'hsl(var(--color-accent-200) / <alpha-value>)',
          300: 'hsl(var(--color-accent-300) / <alpha-value>)',
          400: 'hsl(var(--color-accent-400) / <alpha-value>)',
          500: 'hsl(var(--color-accent-500) / <alpha-value>)',
          600: 'hsl(var(--color-accent-600) / <alpha-value>)',
          700: 'hsl(var(--color-accent-700) / <alpha-value>)',
          800: 'hsl(var(--color-accent-800) / <alpha-value>)',
          900: 'hsl(var(--color-accent-900) / <alpha-value>)',
        },
        success: {
          50: 'hsl(var(--color-success-50) / <alpha-value>)',
          100: 'hsl(var(--color-success-100) / <alpha-value>)',
          200: 'hsl(var(--color-success-200) / <alpha-value>)',
          300: 'hsl(var(--color-success-300) / <alpha-value>)',
          400: 'hsl(var(--color-success-400) / <alpha-value>)',
          500: 'hsl(var(--color-success-500) / <alpha-value>)',
          600: 'hsl(var(--color-success-600) / <alpha-value>)',
          700: 'hsl(var(--color-success-700) / <alpha-value>)',
          800: 'hsl(var(--color-success-800) / <alpha-value>)',
          900: 'hsl(var(--color-success-900) / <alpha-value>)',
        },
        gray: {
          50: 'hsl(var(--color-gray-50) / <alpha-value>)',
          100: 'hsl(var(--color-gray-100) / <alpha-value>)',
          200: 'hsl(var(--color-gray-200) / <alpha-value>)',
          300: 'hsl(var(--color-gray-300) / <alpha-value>)',
          400: 'hsl(var(--color-gray-400) / <alpha-value>)',
          500: 'hsl(var(--color-gray-500) / <alpha-value>)',
          600: 'hsl(var(--color-gray-600) / <alpha-value>)',
          700: 'hsl(var(--color-gray-700) / <alpha-value>)',
          800: 'hsl(var(--color-gray-800) / <alpha-value>)',
          900: 'hsl(var(--color-gray-900) / <alpha-value>)',
        },
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
    },
  },
  plugins: [],
}
